# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90aa8d5d092a82a0ea1b12211a500bd6d1c59c6f38536f41099d654e53fdba0af804d21f6a4ad9e85703830ee6ac8decac2f45da2ad5c10661bce34f426c7da8

test:
  secret_key_base: 6d7afc48b531f2e5b194b02f63836ca344b4dbe3de76ef116933fca848c0bb2b66d626a3143f2cbac172c69f943ec90bb7af7032764988879f7fb45056a2681b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
